/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/texts/artist_text.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Artist_Text = (props) => {
  const { nodes, materials } = useGLTF('./texts/artist_text.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.텍스트001.geometry} material={materials.매테리얼} position={[-1.161, 1.194, -0.032]} rotation={[1.527, 0, 0]} />
      <mesh geometry={nodes.텍스트.geometry} material={materials['매테리얼.001']} rotation={[1.567, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./texts/artist_text.glb')

export default Artist_Text
