/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/texts/review_text.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Review_Text = (props) => {
  const { nodes, materials } = useGLTF('./texts/review_text.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.인기리뷰.geometry} material={materials.매테리얼} position={[-1.124, 0.861, 0.007]} rotation={[1.527, 0, 0]} />
      <mesh geometry={nodes.텍스트.geometry} material={materials['매테리얼.001']} rotation={[1.567, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./texts/review_text.glb')

export default Review_Text
