/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/rock/rock_1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Rock_1 = (props) => {
  const { nodes, materials } = useGLTF('./models/rock/rock_1.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={2.443}>
        <mesh geometry={nodes.Rock_3.geometry} material={materials.Stone_Dark} rotation={[-Math.PI / 2, 0, 0]} scale={[390.097, 390.096, 390.096]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/rock/rock_1.glb')

export default Rock_1
