/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import { useGLTF } from "@react-three/drei";
import React from "react";

const Ship = (props) => {
  const { nodes } = useGLTF("./models/ship/ship.glb");

  // console.log(nodes);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.GeoSphere002_1.geometry}
      >
        <meshStandardMaterial color="#BDCFFC" />
      </mesh>
      <mesh
        geometry={nodes.GeoSphere002_1_1.geometry}
      >
        <meshStandardMaterial color="#969697" />
      </mesh>
      <mesh
        geometry={nodes.GeoSphere002_1_2.geometry}
      >
        <meshStandardMaterial color="black" />
      </mesh>
      <mesh
        geometry={nodes.GeoSphere002_1_3.geometry}
      >
        <meshStandardMaterial color="#144CDE" />
      </mesh>
      <mesh
        geometry={nodes.GeoSphere002_1_4.geometry}
      >
        <meshStandardMaterial color="#FF9F32" />
      </mesh>
      <mesh
        geometry={nodes.GeoSphere002_1_5.geometry}
      >
        <meshStandardMaterial color="#969697" />
      </mesh>
      <mesh
        geometry={nodes.GeoSphere002_1_6.geometry}
      >
        <meshStandardMaterial color="white" />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/ship/ship.glb");

export default Ship