// import Navbar from "@/components/Navbar";
import React from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css';
import ToastProvider from '@/components/ToastProvider';
import { PlayProvider } from '@/components/Threejs/contexts/PlayProvider';
import getCurrentUser from './actions/getCurrentUser';
import AuthSession from './AuthSession';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({children}:Readonly<{children: React.ReactNode;}>){
  const containerStyle = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  };

  return (
    <html>
        <Head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
          </Head>
          <body>
            <main>
                <AuthSession>
                  <PlayProvider>
                    <ToastProvider />
                      <Navbar />  
                      <div style={containerStyle}>
                        {children}
                      </div>
                      <Footer />
                  </PlayProvider>
                </AuthSession>
            </main>
          </body>
    </html>
  );
}