// import Navbar from "@/components/Navbar";
import Head from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css';
import ToastProvider from '@/components/ToastProvider';
import getCurrentUser from './actions/getCurrentUser';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({children})
{

  return (
    <html>

        <Head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
          </Head>
          <body>
            <main>
                    <ToastProvider />
                        <Navbar/>
                        {children}
            </main>
            <Footer />
          </body>

      
    </html>
  );
}